version: "3.2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: proyecto-django-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proyecto-django-internal
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
    depends_on:
      - proyecto-django

  proyecto-django:
    build: .
    container_name: proyecto-django
    env_file:
      - ./src/.env
    command: ["run-runserver"]
    stdin_open: true
    tty: true
    networks:
      - proyecto-django-internal
    ports:
      - 8080:8000
    environment:
      - VIRTUAL_HOST=proyecto-django.dev
      - VIRTUAL_PORT=8000
    depends_on:
      - redis
      - postgres
      - celery
    volumes:
      - ./src:/app/
      - ./media:/data/media

  celery:
    build: .
    container_name: proyecto-django-celery
    env_file:
      - ./src/.env
    command: ["run-celery"]
    networks:
      - proyecto-django-internal
    depends_on:
      - redis
      - celery-beat
      - celery-flower
    volumes:
      - ./src:/app/
      - ./media:/data/media

  celery-flower:
    build: .
    container_name: proyecto-django-celery-flower
    env_file:
      - ./src/.env
    command: ["run-celery-flower"]
    networks:
      - proyecto-django-internal
    ports:
      - 5555:5555
    depends_on:
      - redis
    volumes:
      - ./src:/app/
      - ./media:/data/media

  celery-beat:
    build: .
    container_name: proyecto-django-celery-beat
    env_file:
      - ./src/.env
    command: ["run-celery-beat"]
    networks:
      - proyecto-django-internal
    depends_on:
      - redis
    volumes:
      - ./src:/app/
      - ./media:/data/media

  postgres:
    image: postgres:9.6.6-alpine
    container_name: proyecto-django-postgres
    env_file:
      - ./src/.env
    networks:
      - proyecto-django-internal
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.2.8-alpine
    container_name: proyecto-django-redis
    volumes:
      - ./data/redis:/data
    networks:
      - proyecto-django-internal

networks:
  proyecto-django-internal: {}
